-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: 9ce45609a92f648c87b42207410386fd69a5d1e5
    hooks:
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E309']
    -   id: trailing-whitespace
    -   id: flake8
        args: ['--exclude=node_modules']
