language: python
python:
  - "3.4"

services:
  - mongodb
  - redis-server

env:
  - TOX_ENV=py27
  - TOX_ENV=pypy

# command to install dependencies
install:
  - pip install flake8
  - pip install coveralls
  - pip install tox

# command to run checkers
script:
  - flake8 .
  - touch firefly/local_settings.py
  - tox -e $TOX_ENV

after_success:
  - coveralls
