language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r py2-requirements.txt; fi
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
# command to run checkers
script:
  - flake8 .
after_success:
  - coveralls